create_apopintment:
    path: /appointments
    controller: App\Controller\API\AppointmentController:createApointment
    methods: POST
list_apopintment:
    path: /appointments
    controller: App\Controller\API\AppointmentController:listApointment
    methods: GET
list_workplace:
    path: /workplace
    controller: App\Controller\API\AppointmentController:listWorkplace
    methods: GET
